### ISSUE TITLE
user-can-search-show.md

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/ShowGeek#1]
## 💰 Motivation

A user is able to to find results for the tv show they are searching for

## 📐 Plan

Allow a user to click on the search bar and type in the title of a tv show.
## 🖼️ Wireframes

Mobile view:

![user can view their entries mobile](https://user-images.githubusercontent.com/113082803/201793265-4fc11585-4a02-45db-bc16-0c533f50979a.png)

Desktop view:

![user can view their entries desktop](https://user-images.githubusercontent.com/113082803/201793460-66edb9cc-ba19-487a-9aff-88e1f20277ae.png)

## ✅ Task List

- [x] Add a div with data-view="home" in the HTML.
- [x] Add an input with type="text".
- [x] Add a submit with the name "search".
- [x] Make sure that the view will change according to mobile and desktop views.
- [x] Create a function on main.js to verify that the search button is responding to the search bar with a string.
- [x] Create a function that will verify whether the string matches a show title in the API database.
- [x] Make sure function is working by logging a show that matches a title in the database.
- [x] Remove any unnecessary CSS and console.log on main.js.
- [x] Perform another test to make sure there are no console errors.
