### ISSUE TITLE
search-results-displayed.md

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/ShowGeek#2]
## 💰 Motivation

After a search is initiated, the title of the show, an image and a summary of the show will be displayed if the string matches a show in the API database.

## 📐 Plan

Make sure the layout of the results are displayed like the wireframes

## 🖼️ Wireframes

Mobile view:

![user can view their entries mobile](https://user-images.githubusercontent.com/113082803/201736440-ebccdd21-78c6-4216-a9ff-1c4923bc1c53.png)

Desktop view:

![user can view their entries desktop](https://user-images.githubusercontent.com/113082803/201736834-bdd128b6-f531-4ecd-aa12-f26ea42763a7.png)

## ✅ Task List

- [x] Create a CSS class `'hidden'` and apply it to the `data-view="home"`. 
- [x] Add a sibling `div` with `data-view="result"`.
- [x] Add a left arrow on the top left corner of the body page and make sure this is clickable.
- [x] Create an empty `div` under the left arrow and query this to the DOM.
- [x] Add a sample entry with the title of the show, image and paragraph to the empty div.
- [x] Under the paragraph, create a sample button for `button: 'Add to list'`.
- [x] Define a function `searchResult` that takes the value of the search input and creates a DOM tree with the name, image link, summary of the show, and the `add` button.
- [x] Add an event listener to the `add` button to ensure that it is clickable.
- [x] Append the title, image and summary to the empty `div`.
- [x] Make sure the styling of created elements like correct before removing sample.
- [x] Add anchors to the `home icon` and `back icon` to switch views when clicked on.
- [x] Remove any unnecessary CSS and console.log on main.js.
- [x] Perform another test to make sure there are no console errors.
