### ISSUE TITLE
user-can-add-review.md

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/ShowGeek#3]
## 💰 Motivation

When a user clicks on the "add to list" button, they will be prompted with a modal to add a review and must click confirm to add to their list.

## 📐 Plan

Add a modal that will pop up when a user clicks on the "add to list" button and make sure that there is a working drop down menu and text area.

## 🖼️ Wireframes

Mobile view:

![user can view their entries mobile](https://user-images.githubusercontent.com/113082803/201737632-0493daca-c1a8-48f3-9128-4e0a8559791b.png)

Desktop view:

![user can view their entries desktop](https://user-images.githubusercontent.com/113082803/201738472-50c1dfb2-7018-40de-8b95-ee96d861a3b3.png)

## ✅ Task List

- [x] Create a new `div` under the  empty `div: DOM Tree` and add `data-view="add-list"` to the new `div`.
- [x] Inside the newly created div, create a modal block.
- [x] On the first row, add a header to this modal.
- [x] On the second row, add a `<select>` element with a placeholder: `Number of stars`, and options for the numbers 0-5.
- [x] on the third row, add a textarea for users to write a comment.
- [x] On the last row, add a `cancel` and `confirm` buttons.
- [x] Make sure that the modal its centered on both mobile and desktop views
- [x] Add view swap functions to the `cancel` to make sure the modal closes when clicked on.
- [x] Add a review to a show to create a sample review and make sure that it saved into an `object`.
- [x] Save the `entryId` into the object and increment the next number.
- [x] Create a new sibling `div: data-view="list"` on the HTML and test that this page by setting the other `data-view` pages to hidden.
- [x] Add an anchor to the list icon so that it switches view to the list view.
- [x] Define a function that submits a form when the `confirm` button is clicked.
- [x] Remove any unnecessary CSS and console.log on main.js.
- [x] Perform another test to make sure there are no console errors.
