### ISSUE TITLE
user-can-view-list.md

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/ShowGeek#4]
## 💰 Motivation

After a user clicks on "add to list" and "confirmed" their review, they should be navigated to the list view of all shows that were added. Or when the list icon is clicked, it should show the same result.

## 📐 Plan

Make sure the list icon is clickable and navigates to the list view and that adding a new entry will load the list view

## 🖼️ Wireframes

Mobile view:

![user can view their entries mobile](https://user-images.githubusercontent.com/113082803/201738944-fdf12181-f22f-4a3c-b6e0-73efa9ae9849.png)

Desktop view:

![user can view their entries desktop](https://user-images.githubusercontent.com/113082803/201739135-03ddc1b4-fdcc-407f-9b1d-17e06af5c9fd.png)

## ✅ Task List

- [x] Add an empty `div` under the `div: data-view="list"`.
- [x] Under the sibling `div: data-view="list"`, create 2 sample data and style it like the wireframes.
- [x] In the function for the `confirm` button of the modal, make sure that the `object` for the show review is prepended into the entries array of the data model.
- [x] When a user clicks on the `confirm` button, it should switch views to the list view.
- [x] Make sure that after the `confirm` form is submitted, modal inputs are cleared before searching a new show.
- [x] Define a new function that creates a new DOM tree.
  - [x] Create a new element for a `container` div that acts as the entry background.
  - [x] Create a row that contains the image, title and comment.
  - [x] Create a row that contains the star rating, edit icon and delete icon.
- [x] Append the DOM tree to the empty `div: data-view='list"`, if it looks like the wireframe, delete the sample data.
- [x] Make sure that the new DOM tree fits for both mobile and desktop views.
- [x] Make sure that the user can stay on the same page when refreshing the screen.
- [x] Make sure that new reviews are being created and appended to the `list` view.
- [x] Remove any unnecessary CSS and console.log on main.js.
- [x] Perform another test to make sure there are no console errors.
