### ISSUE TITLE
user-can-modify-list-items.md

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/ShowGeek#5]
## 💰 Motivation

A user can click on either the pencil or trash icon to edit or delete, respectively. 

## 📐 Plan

When clicked on the pencil icon, a modal should pop up and preload previous data entered for the review and any changes should be saved. When clicked on the trash icon, it should remove the show from the list.

## 🖼️ Wireframes

Mobile view:

![user can view their entries mobile](https://user-images.githubusercontent.com/113082803/201740539-ac3fae89-a663-4d0c-b1bf-7baf579e1a7d.png)

Desktop view:

![user can view their entries desktop](https://user-images.githubusercontent.com/113082803/201740977-d072b915-1ed9-4ba9-9140-c308a5d763bd.png)

## ✅ Task List

- [x] DOM query the created icons for edit and delete.
- [x] Console log a `click` and `event targets` for each icon to verify that these buttons work. 
- [x] When clicked on the `edit icon`, make sure that the same `confirmation` modal from results pops up.
- [x]  Find the matching entry object in the data model and assign it to the data model's editing property if an edit icon was clicked.
- [x] Make sure the previous entries are preloaded into the modal.
- [x] If the user clicks on cancel, it will close the modal.
- [x]  Update the entry form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.
- [x] Create a new `div: data-view="delete"` and hide all views to make sure style fits page.
- [x] When clicked on the `delete icon`, make sure another confirmation modal with `cancel` or `delete` pops up.
- [x] When the user clicks on cancel, it will close the modal.
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the list view if the user clicks Delete.
- [x]  Remove any unnecessary CSS and console.log on main.js.
- [x] Perform another test to make sure there are no console errors.
